language: java
services:
  - postgresql
before_script:
  - psql -c 'create database flooring_master;' -U postgres
env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"
  - DATABASE_URL=postgres://postgres:@localhost:5432/flooring_master  