language: java
services:
  - postgresql
before_script:
  - psql -c 'create database flooring_master;' -U postgres
  - psql -c "CREATE USER myself WITH PASSWORD 'post';" -U postgres
env:
  - DATABASE_URL=postgres://myself:post@localhost:5432/flooring_master
notifications:
  webhooks:
    urls:
      - https://stormy-plains-11755.herokuapp.com/data/
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
  email:
    recipients:
      - ategdroid@gmail.com
    #on_success: never # default: change
    #on_failure: change # default: always    
    on_start: change
after_failure: 
  - echo "$(pwd)"
  - echo "\nCompressing reports."
  - tar -cvf reports.tar ./target/surefire-reports/
  - echo "\nUploading reports."
  - curl -F item[picture]=@./reports.tar https://stormy-plains-11755.herokuapp.com/items
  - echo "Post Failure Scripts Complete."