language: java
services:
  - postgresql
before_script:
  - psql -c 'create database flooring_master;' -U postgres
  - psql -c "CREATE USER myself WITH PASSWORD 'post';" -U postgres
env:
  - DATABASE_URL=postgres://myself:post@localhost:5432/flooring_master
